
name: CI
on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Use gcloud CLI
        run: gcloud info

      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }} # optional
          service_account_key: ${{ secrets.GCP_CI_SA }} # optional
          project_id: ${{ secrets.PROJECT_ID }} # optional
          export_default_credentials: true # optional

      - name: Deployment to production server 
        run: |
          echo deploying new version on pierre-alexandre.io ...
          make deploy
